export default {
  FETCH_PRODUCT_FAIL: "FETCH PRODUCT FAIL",
  UPDATE_PRODUCT_FAIL: "UPDATE_PRODUCT_FAIL",
  DELETE_PRODUCT_FAIL: "DELETE_PRODUCT_FAIL",
  FETCH_CATEGORIES_FAIL: "FETCH_CATEGORIES_FAIL",
};